# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow when a stable or pre-release release is published
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    if: github.repository == 'andyalm/faissmask'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      Configuration: Release
      PackageReleaseNotes: ${{ github.event.release.body }}
      PackageReleaseTag: ${{ github.event.release.tag_name }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Build
        run: dotnet build
        
      - name: Publish FaissMask to nuget.org
        run: dotnet nuget push $(ls FaissMask/bin/${{ env.Configuration }}/*.nupkg) -k ${{ secrets.NUGET_FEED_KEY }} -s https://api.nuget.org/v3/index.json
   
    environment:
      name: nuget.org
      url: https://nuget.org/packages/FaissMask